### ISSUE TITLE
Create blog post should create an _id

### ISSUE THREAD

**Issue by PalatinCoder** [PalatinCoder/DieBernds#4]

**Comment by dominik-code** [comment]
Hab eine Lösung gefunden. Es scheint sich um eine MongoDB ObjectID zu handeln. Diese kannst du ganz einfach mit folgendem Code erzeugen:

`var ObjectID = require('mongodb').ObjectID;`
und dann an der entsprechenden Stelle:
`_id : new ObjectID(),` im neuen Blogeintrag.

Mit freundlichen Grüßen

Dominik

**Comment by d-Rickyy-b** [comment]
@dominik-code Lol :D

**Comment by d-Rickyy-b** [comment]
@dominik-code Danke dir Dominik :)
